### ISSUE TITLE
setup.py fails to install the project

### ISSUE THREAD

**Issue by ianbtr** [SantanderMetGroup/WRF4G#27]
Running `python setup.py install` gives the following:

```
running install
error: https://meteo.unican.es/work/WRF4G/repository.tar.gz: None
```

Attempting to download the specified file from that URL also does not work.

**Comment by jesusff** [comment]
There is a dirty mix of Python 2 and 3 in setup.py so the installation fails even if the URL for repository.tar.gz is now available.

Installation options (especially from source) need to be clarified.
