### ISSUE TITLE
WRF4G and DRM4G commands overload

### ISSUE THREAD

**Issue by cofinoa** [SantanderMetGroup/WRF4G#42]
Some `drm4g` and `wrf4g` commands are equivalent. 

A better integration of `drm4g` and `wrf4g` CLI needs to be carry on.

**Comment by fernanqv** [comment]
(wrf4g-py36) [vagrant@centos7 ~]$ wrf4g resource
RESOURCE            STATE
RESOURCE            STATE
localmachine        enabled
localmachine        enabled
